name: "gs-sds-generation"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [2.5, 2.5]
  fovy_range: [60, 60]
  elevation_range: [0, 0]
  light_sample_strategy: "dreamfusion"
  eval_camera_distance: 2.5
  eval_fovy_deg: 60
  eval_elevation_deg: 0
  rays_d_normalize: false
  center_perturb: 0
  up_perturb: 0
  camera_perturb: 0
  azimuth_range: [-15, 15] 
  val_azimuth_range: [-15, 15]
  insert_zero: true

system_type: "scene-lang-system"
system:
  encoder_hidden_dims: [256, 128, 32, 3]
  decoder_hidden_dims: [32, 128, 256, 512]
  xyz_noise_ratio: [1000, 0.0, 0.0, 3000]
  drop_ooi_ratio: 0.3
  crop_with_lang: true
  densify: false

  geometry_type: "gaussian-splatting"
  geometry:
    ooi_bbox: [360,370,730,590]
    geometry_convert_from: depth:assets/anime.png
    position_lr: [0, 0.001, 0.00002, 1000]
    scaling_lr: 0.05
    feature_lr: 0.01
    opacity_lr: 0.05
    rotation_lr: 0.005
    lang_lr: 0.0003
    densification_interval: 300
    prune_interval: 300
    opacity_reset_interval: 50000000
    densify_from_iter: 500
    densify_until_iter: ${trainer.max_steps}
    prune_from_iter: 500
    prune_until_iter: ${trainer.max_steps}
    densify_grad_threshold: 0.01
    min_opac_prune: 0.005
    split_thresh: 0.02
    radii2d_thresh: 1000

    init_num_pts: 4096
    pc_init_radius: 0.8
    opacity_init: 0.2
   
    empty_prompt: ${system.empty_prompt}
    prompt: ${system.prompt_processor.prompt}
    max_scaling: 0.2

  renderer_type: "diff-gaussian-rasterizer"
  renderer:
    debug: false
    invert_bg_prob: 0.5

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    # pretrained_model_name_or_path: "/mnt/petrelfs/zhangqihang/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base"
    prompt: ???
  empty_prompt: "empty"

  guidance_type: "stable-diffusion-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    # pretrained_model_name_or_path: "/mnt/petrelfs/zhangqihang/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base"
    guidance_scale: 5.0
    weighting_strategy: sds
    min_step_percent: 0.02
    max_step_percent: [0, 0.5, 0.1, 1000]  
    csd: false
  
  # guidance_type: "stable-diffusion-vsd-guidance"
  # guidance:
  #   pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
  #   pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
  #   guidance_scale: 7.5
  #   min_step_percent: 0.02

  exporter_type: "gaussian-mesh-exporter"

  sam_clip:
    use_mobile_sam: False

  loggers:
    wandb:
      enable: false
      project: '3ditscene'
      name: "${tag}"

  loss:
    lambda_sds: 0.01
    lambda_ref: 1000
    lambda_depth: 0.0
    lambda_position: 1.0
    lambda_opacity: 0.0001
    lambda_scales: 0.0001
    lambda_tv_loss: 1.0
    lambda_depth_tv_loss: 1.0
    lambda_scaling: 0.0

trainer:
  max_steps: 1500
  log_every_n_steps: 1
  num_sanity_val_steps: 110
  val_check_interval: 500
  enable_progress_bar: true
  precision: 32-true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: 1000
  save_weights_only: true
  # every_n_train_steps: ${trainer.max_steps}
